apiVersion: v1
kind: Secret
metadata:
  name: api-auth-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: microservices
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.apiAuth.apiKey }}
