apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  DB_CONNECTION_STRING: "Host={{ .Values.postgres.service.name }};Port={{ .Values.postgres.service.port }};Database={{ .Values.postgres.credentials.database }};Username={{ .Values.postgres.credentials.user }};Password={{ .Values.postgres.credentials.password }}"
