apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.productApi.name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.productApi.name }}
data:
  PORT: "{{ .Values.productApi.service.targetPort }}"
  ASPNETCORE_ENVIRONMENT: "{{ .Values.productApi.config.aspnetcoreEnvironment }}"
  ASPNETCORE_URLS: "http://+:{{ .Values.productApi.service.targetPort }}"
  DB_HOST: "{{ .Values.postgres.service.name }}"
  DB_PORT: "{{ .Values.postgres.service.port }}"
