apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productApi.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.productApi.name }}
spec:
  type: {{ .Values.productApi.service.type }}
  selector:
    app: {{ .Values.productApi.name }}
  ports:
  - port: {{ .Values.productApi.service.port }}
    targetPort: {{ .Values.productApi.service.targetPort }}
    protocol: TCP
