apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
  namespace: microservices
  labels:
    app: order-api
data:
  PORT: "8081"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8081"
  PRODUCT_API_URL: "http://product-api"
