apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: microservices
  labels:
    app: product-api
data:
  PORT: "8080"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  DB_HOST: "postgres"
  DB_PORT: "5432"
